version: '3.9'

x-environment: &common_env
  TS_URI: postgres://postgres:postgres@timescale:5432/postgres
  PG_URI: postgres://postgres:postgres@timescale:5432/postgres
  REDIS_URI: redis://redis:6379/0
  GEN_ADDR: generator:5001

services:
  timescale:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_PASSWORD: postgres
      TIMESCALEDB_TELEMETRY: off
    networks:
      - wh_internal
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'postgres']
  redis:
    image: redis:7-alpine
    networks:
      - wh_internal
    command: redis-server --maxmemory-policy allkeys-lru --maxmemory 1gb
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
  generator:
    image: ghcr.io/noquark/wormholes:latest
    networks:
      - wh_internal
    environment:
      <<: *common_env
      MODE: generator # required
    depends_on:
      timescale:
        condition: 'service_healthy'
      redis:
        condition: 'service_healthy'
  creator:
    image: ghcr.io/noquark/wormholes:latest
    ports:
      - 5002:5002
    networks:
      - wh_internal
    environment:
      <<: *common_env
      MODE: creator # required
    depends_on:
      generator:
        condition: 'service_started'
  redirector:
    image: ghcr.io/noquark/wormholes:latest
    ports:
      - 5000:5000
    networks:
      - wh_internal
    environment:
      <<: *common_env
      MODE: redirector # required
    depends_on:
      timescale:
        condition: 'service_healthy'
      redis:
        condition: 'service_healthy'

networks:
  wh_internal:
    external: false
    name: wh-internal
