version: '3.9'

x-environment: &default_env
  - TS_URI=postgres://postgres:postgres@timescale:5432/postgres
  - PG_URI=postgres://postgres:postgres@postgres:5432/postgres
  - REDIS_URI=redis://:redis@redis:6379/0
  - GEN_ADDR=generator:5001

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - wh_internal
    configs:
      - source: postgres
        target: /etc/postgresql/postgresql.conf
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'postgres']
  timescale:
    image: timescale/timescaledb:latest-pg13
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - wh_internal
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'postgres']
  redis:
    image: redis:6-alpine
    networks:
      - wh_internal
    configs:
      - source: redis
        target: /usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
  generator:
    image: ghcr.io/mohitsinghs/wormholes:latest
    command: ./wormholes -as generator
    networks:
      - wh_internal
    environment: *default_env
    depends_on:
      postgres:
        condition: 'service_healthy'
      timescale:
        condition: 'service_healthy'
      redis:
        condition: 'service_healthy'
  creator:
    image: ghcr.io/mohitsinghs/wormholes:latest
    command: ./wormholes -as creator
    ports:
      - 5002:5002
    networks:
      - wh_internal
    environment: *default_env
    depends_on:
      postgres:
        condition: 'service_healthy'
      timescale:
        condition: 'service_healthy'
      redis:
        condition: 'service_healthy'
      generator:
        condition: 'service_started'
  director:
    image: ghcr.io/mohitsinghs/wormholes:latest
    command: ./wormholes -as director
    ports:
      - 5000:5000
    networks:
      - wh_internal
    environment: *default_env
    depends_on:
      - postgres
      - timescale
      - redis
      - generator

configs:
  postgres:
    file: $PWD/conf/postgres.conf
  redis:
    file: $PWD/conf/redis.conf
networks:
  wh_internal:
    external: false
    name: wh-internal
