name: docker

on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - 'go.*'
      - 'Dockerfile'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push director
        id: build_director
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=gha,scope=director
          cache-to: type=gha,scope=director,mode=max
          target: director
          tags: ghcr.io/mohitsinghs/wh-director:latest

      - name: Build and push generator
        id: build_generator
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=gha,scope=generator
          cache-to: type=gha,scope=generator,mode=max
          target: generator
          tags: ghcr.io/mohitsinghs/wh-generator:latest

      - name: Build and push creator
        id: build_creator
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=gha,scope=creator
          cache-to: type=gha,scope=creator,mode=max
          target: creator
          tags: ghcr.io/mohitsinghs/wh-creator:latest
